{{- if .Values.maintainerr.enable }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maintainerr-ingress
  {{- with .Values.maintainerr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "maintainerr.selectorLabels" . | nindent 4 }}
    {{- with .Values.maintainerr.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.maintainerr.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.maintainerr.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: maintainerr-service
            port:
              number: {{ .Values.maintainerr.service.port }}
        path: /
        pathType: Prefix
  {{- with .Values.maintainerr.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}
